package crussty.batch;

/**
 * Compile-time stub for the batch dispatch bridge (G4 demonstrator compile
 * dependency of ImprovedNoiseBatchOps). NOT shipped: the real class is
 * defined at runtime into the bootstrap loader by the plugin
 * (src/batch_api.rs — `crussty/batch/PaperNativeBatchDispatch` with natives
 * `run` + `abiVersion` registered on it). Kernel loaders are parent-first,
 * so the bootstrap-defined bridge resolves from ImprovedNoiseBatchOps'
 * kernel loader unchanged.
 *
 * Signatures must stay in lock-step with src/batch_api.rs (RUN_SIG and the
 * export symbols there); ImprovedNoiseBatchOps pins the ABI word. The stub
 * class is PUBLIC because the runtime bridge generated by bridge_class.rs
 * is public (and javac requires the compile-time shape to match).
 */
public final class PaperNativeBatchDispatch {
    private PaperNativeBatchDispatch() {}
    public static native int run(int[] kernelIds, long[] args0, long[] args1,
                                 int[] argCounts, long[] outs, int[] outOffsets);
    public static native int abiVersion();
}
