//! Chunk-status enable gate -- the do-not-wire doctrine applied to CHUNK lanes.
//!
//! Mirrors `crussty/src/kernel_policy.rs` (the enforced do-not-wire gate for
//! native kernels) but at the coarser granularity this mandate needs: a
//! decision per CHUNK STATUS LANE (a named generation step, e.g.
//! `structures/jigsaw`), not per kernel. The doctrine is identical:
//!
//! * a lane may be *registered* (the Rust implementation exists and is
//!   callable) without being *enabled* (routed live);
//! * enabling is decided ONLY by this gate, and the gate refuses everything
//!   that is not explicitly proven zero-diff (`NATIVE_READY` carries the
//!   evidence tag per entry);
//! * lanes with known divergence or unreplicated semantics live in
//!   `DO_NOT_ENABLE` and can never be enabled while listed -- a
//!   `DO_NOT_ENABLE` hit beats a `NATIVE_READY` hit by evaluation order.
//!
//! Policy (evaluated in order):
//!
//! | Condition | Decision |
//! |---|---|
//! | mode `Off` (the default) | `KeepJava("gate off (default-dormant)")` |
//! | lane in `DO_NOT_ENABLE` | `KeepJava(reason)` |
//! | lane in `NATIVE_READY` | `Allow` |
//! | anything else (unknown / unproven) | `KeepJava("not proven (zero-diff gate not passed)")` |
//!
//! Note the deliberate asymmetry with `kernel_policy`: there, `Off` is a
//! DANGEROUS bypass (Allow-everything) for A/B benchmarking. Here `Off` is
//! the SAFE default -- the whole factory stays dormant and every chunk is
//! generated by Java. There is no bypass: an unproven lane cannot be forced
//! native by any env value (an unknown value NEVER widens the gate).
//!
//! The fallback law is the reason the default must be dormant: any chunk
//! containing unsupported content (uncovered structures/features, blending,
//! foreign BlockPopulator) is generated by Java, and native coverage % is
//! always reported (mandate invariant I8 -- see [`coverage_ratio`] and
//! `crate::coverage`).
//!
//! Env override `CRUSSTY_CHUNK_FACTORY` (read once, cached in a `OnceLock`):
//!
//! | Value | Behavior |
//! |---|---|
//! | unset / empty / `off` | `Off` -- default-dormant, everything Java |
//! | `strict` | enforce: only `NATIVE_READY` lanes go native (silent) |
//! | `audit` | strict + log every decision (`audit_wire` / wiring sites) |
//! | anything else | `Off` (fail-safe: an unknown value never widens the gate) |
//!
//! Registry lookups are allocation-free and lock-free: static slices,
//! linear scan, `&'static str` reasons (the `Decision` never allocates).

use std::sync::OnceLock;

/// Env var consulted (once) for the gate mode.
const MODE_ENV: &str = "CRUSSTY_CHUNK_FACTORY";

/// Log prefix, mirroring the plugin's other subsystems.
const LOG_PREFIX: &str = "[crussty-plugin] chunk-factory:";

/// How the gate behaves. Default `Off` (default-dormant).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PolicyMode {
    /// Default. The factory is dormant: every chunk stays on the Java path.
    /// NOT a dangerous bypass (contrast `kernel_policy`) -- it is the safe
    /// state, mirroring the G2 dormancy doctrine.
    Off,
    /// Enforce: a lane goes native only if it is registered in
    /// `NATIVE_READY` (and not in `DO_NOT_ENABLE`). Silent.
    Strict,
    /// `Strict` AND every decision is logged (wiring-site audits; never
    /// crashes -- a refusal is a returned `Decision`, the caller keeps the
    /// Java path).
    Audit,
}

/// The gate verdict for one chunk-status lane.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Decision {
    /// Generate this lane natively in Rust (proven zero-diff, enabled mode).
    Allow,
    /// Keep the vanilla Java path for this lane. `reason` says why
    /// (`&'static str` -- the decision is allocation-free).
    KeepJava { reason: &'static str },
}

impl Decision {
    pub fn is_allowed(&self) -> bool {
        matches!(self, Decision::Allow)
    }
}

/// Registry of lanes PROVEN zero-diff and therefore native-eligible (under
/// a non-`Off` mode). Entries are `(chunk_status_step, evidence_tag)`.
///
/// The evidence tag must point at the zero-diff run that proved the lane:
/// harness id, chunk/seed/datapack matrix, date. A lane is promoted here
/// ONLY after the GATE passes for it (>=10^4 chunks x >=5 seeds x
/// {vanilla, Terralith, Tectonic} = 0 divergences); promotion is undone the
/// same way -- remove the row and the lane falls back to Java at the next
/// boot.
///
/// PHASE 0: intentionally EMPTY. No lane is proven; nothing may claim to be.
/// Do not seed this table with placeholder rows -- an Allow must always be
/// backed by real evidence. Tests treat the empty registry as the spec:
/// under `Strict`, everything is `KeepJava("not proven")`.
pub static NATIVE_READY: &[(&str, &str)] = &[];

/// Registry of lanes with known divergence or unreplicated semantics --
/// refused with their reason even if someone later (mistakenly) lists them
/// in `NATIVE_READY` too: `DO_NOT_ENABLE` is evaluated FIRST.
///
/// Seeded in Phase 0 with forward-looking documentation of the known hard
/// parts (not measurements): each row is a lane we already KNOW must not go
/// native until its specific semantics are replicated and gated.
pub static DO_NOT_ENABLE: &[(&str, &str)] = &[
    (
        "structures/jigsaw",
        "Phase 5 not implemented -- Java fallback mandatory",
    ),
    (
        "legacy_blending",
        "quart-pos blending owner semantics not replicated yet",
    ),
];

/// Parse a mode from a raw env value. Unset/empty/`off`/unrecognized -> Off
/// (fail-safe: the default is dormant and an unknown value must never widen
/// the gate -- there is no env value that forces native generation).
///
/// `pub(crate)` (not private) so the crate-level smoke test in `lib.rs` can
/// assert the shipped default (`None` -> `Off`) without mutating process
/// env inside tests: tests exercise the PARSER, never `mode()`'s cached env
/// read.
pub(crate) fn parse_mode(raw: Option<&str>) -> PolicyMode {
    match raw.map(|v| v.trim().to_ascii_lowercase()) {
        Some(v) if v == "strict" => PolicyMode::Strict,
        Some(v) if v == "audit" => PolicyMode::Audit,
        // "off", empty, unset, garbage -> Off (default-dormant, fail-safe)
        _ => PolicyMode::Off,
    }
}

/// The process-wide mode, read from `CRUSSTY_CHUNK_FACTORY` exactly once.
/// `Off` is the default and stays silent (it is the normal state); the
/// widened modes log one boot line so an operator can see the gate is open.
pub fn mode() -> PolicyMode {
    static MODE: OnceLock<PolicyMode> = OnceLock::new();
    *MODE.get_or_init(|| {
        let m = parse_mode(std::env::var(MODE_ENV).ok().as_deref());
        match m {
            PolicyMode::Off => {} // default-dormant: silent
            PolicyMode::Strict => eprintln!(
                "{LOG_PREFIX} strict: {} lane(s) native-ready, {} lane(s) do-not-enable \
                 (unproven lanes keep Java)",
                NATIVE_READY.len(),
                DO_NOT_ENABLE.len()
            ),
            PolicyMode::Audit => eprintln!(
                "{LOG_PREFIX} audit: decisions are logged (still enforced; \
                 {} native-ready / {} do-not-enable)",
                NATIVE_READY.len(),
                DO_NOT_ENABLE.len()
            ),
        }
        m
    })
}

/// Look a lane up in the `DO_NOT_ENABLE` registry. Exact step match,
/// allocation-free linear scan. Returns the refusal reason.
pub fn do_not_enable_entry(step: &str) -> Option<&'static str> {
    DO_NOT_ENABLE
        .iter()
        .find(|(s, _)| *s == step)
        .map(|(_, reason)| *reason)
}

/// Look a lane up in the `NATIVE_READY` registry. Exact step match,
/// allocation-free linear scan. Returns the evidence tag.
pub fn native_ready_entry(step: &str) -> Option<&'static str> {
    NATIVE_READY
        .iter()
        .find(|(s, _)| *s == step)
        .map(|(_, evidence)| *evidence)
}

/// The decision function under explicit registries (pure; used by
/// [`decide_in`] and by tests that need to simulate registry states, e.g.
/// the "in both registries" precedence rule). No allocation, no locks.
fn decide_in_tables(
    mode: PolicyMode,
    step: &str,
    do_not_enable: &[(&'static str, &'static str)],
    native_ready: &[(&'static str, &'static str)],
) -> Decision {
    if mode == PolicyMode::Off {
        // Default-dormant: the factory is off, every chunk is Java's.
        return Decision::KeepJava {
            reason: "gate off (default-dormant)",
        };
    }
    // DO_NOT_ENABLE beats NATIVE_READY: evaluated first, by design.
    if let Some((_, reason)) = do_not_enable.iter().find(|(s, _)| *s == step) {
        return Decision::KeepJava { reason };
    }
    if native_ready.iter().any(|(s, _)| *s == step) {
        return Decision::Allow;
    }
    // Default-safe: unknown / unproven lanes stay on the Java side until a
    // GATE pass promotes them into NATIVE_READY.
    Decision::KeepJava {
        reason: "not proven (zero-diff gate not passed)",
    }
}

/// The decision function under an explicit mode (pure; used by tests and by
/// `decide`).
pub fn decide_in(mode: PolicyMode, step: &str) -> Decision {
    decide_in_tables(mode, step, DO_NOT_ENABLE, NATIVE_READY)
}

/// The decision function (uses the cached env mode).
/// `step` is the chunk-status lane id, e.g. `structures/jigsaw`.
pub fn decide(step: &str) -> Decision {
    decide_in(mode(), step)
}

/// Audit hook for future wiring sites (wherever a chunk path starts routing
/// a lane to the Rust factory): in `Audit` mode logs the decision;
/// otherwise a no-op. Never panics, never changes behavior. Pair with a
/// `debug_assert!(decide(step).is_allowed(), ..)` where the wiring is meant
/// to be whitelisted -- debug builds then catch an accidental demotion.
pub fn audit_wire(step: &str, site: &str) {
    if mode() != PolicyMode::Audit {
        return;
    }
    match decide_in(PolicyMode::Audit, step) {
        Decision::Allow => {
            eprintln!("{LOG_PREFIX} LANE {step} at {site}: native allowed (proven)")
        }
        Decision::KeepJava { reason } => {
            eprintln!("{LOG_PREFIX} LANE {step} at {site}: Java fallback -- {reason}")
        }
    }
}

/// Native coverage ratio for a batch (`0.0..=1.0`). Mandate invariant I8:
/// native coverage % must ALWAYS be reported, never implied -- callers feed
/// this into their own telemetry; the report-level form is
/// `crate::coverage::CoverageReport::coverage_pct`. An empty batch reports
/// `0.0` (no chunks, no coverage claim; never NaN, never silently 1.0).
pub fn coverage_ratio(enabled: usize, total: usize) -> f64 {
    if total == 0 {
        return 0.0;
    }
    enabled as f64 / total as f64
}

#[cfg(test)]
mod tests {
    use super::*;

    // --- registry integrity --------------------------------------------------

    #[test]
    fn registries_are_well_formed_and_disjoint() {
        for (step, reason) in DO_NOT_ENABLE {
            assert!(!step.is_empty(), "DO_NOT_ENABLE has an empty step");
            assert!(!reason.is_empty(), "DO_NOT_ENABLE[{step}] has an empty reason");
            // A do-not-enable lane must never also be native-ready.
            assert!(
                native_ready_entry(step).is_none(),
                "{step} is in both DO_NOT_ENABLE and NATIVE_READY"
            );
        }
        for (step, evidence) in NATIVE_READY {
            assert!(!step.is_empty(), "NATIVE_READY has an empty step");
            assert!(
                !evidence.is_empty(),
                "NATIVE_READY[{step}] has no evidence tag"
            );
            assert!(
                do_not_enable_entry(step).is_none(),
                "{step} is in both NATIVE_READY and DO_NOT_ENABLE"
            );
        }
    }

    #[test]
    fn native_ready_is_empty_in_phase_0() {
        // The GATE has never passed; nothing may claim to be proven. If you
        // are about to delete this assertion, you must have GATE evidence
        // for every row you added.
        assert!(
            NATIVE_READY.is_empty(),
            "Phase 0: NATIVE_READY must stay empty until a lane passes the GATE"
        );
    }

    // --- env parsing (pure; no env mutation, mode() caches once per process) --

    #[test]
    fn unknown_env_value_falls_back_to_off() {
        assert_eq!(parse_mode(None), PolicyMode::Off); // unset
        assert_eq!(parse_mode(Some("")), PolicyMode::Off); // empty
        assert_eq!(parse_mode(Some("off")), PolicyMode::Off);
        assert_eq!(parse_mode(Some(" OFF ")), PolicyMode::Off);
        // Unknown values NEVER widen the gate (fail-safe):
        assert_eq!(parse_mode(Some("1")), PolicyMode::Off);
        assert_eq!(parse_mode(Some("yes")), PolicyMode::Off);
        assert_eq!(parse_mode(Some("allow")), PolicyMode::Off);
        assert_eq!(parse_mode(Some("on")), PolicyMode::Off);
        // The only two widening values:
        assert_eq!(parse_mode(Some("strict")), PolicyMode::Strict);
        assert_eq!(parse_mode(Some(" Strict ")), PolicyMode::Strict);
        assert_eq!(parse_mode(Some("audit")), PolicyMode::Audit);
        assert_eq!(parse_mode(Some("AUDIT")), PolicyMode::Audit);
    }

    // --- core decisions -------------------------------------------------------

    #[test]
    fn off_mode_keeps_everything_java() {
        // Default-dormant: even a hypothetical native-ready lane stays Java.
        let ready = &[("noise/initial_shape", "hypothetical evidence")];
        for step in ["noise/initial_shape", "structures/jigsaw", "example/status", ""] {
            let d = decide_in_tables(PolicyMode::Off, step, DO_NOT_ENABLE, ready);
            assert!(!d.is_allowed(), "{step} must stay Java under Off");
            assert_eq!(
                d,
                Decision::KeepJava {
                    reason: "gate off (default-dormant)"
                }
            );
        }
    }

    #[test]
    fn do_not_enable_beats_native_ready() {
        // If a step were listed in both registries, DO_NOT_ENABLE must win.
        let do_not = &[("lane/x", "known divergence")];
        let ready = &[("lane/x", "contradictory evidence")];
        let d = decide_in_tables(PolicyMode::Strict, "lane/x", do_not, ready);
        assert_eq!(d, Decision::KeepJava { reason: "known divergence" });
        // ... and under Audit, same precedence:
        let d = decide_in_tables(PolicyMode::Audit, "lane/x", do_not, ready);
        assert!(!d.is_allowed());
    }

    #[test]
    fn strict_with_empty_native_ready_keeps_everything_java() {
        // The Phase 0 reality: no lane is proven, so Strict is
        // indistinguishable from Off in effect (but not in intent).
        for (step, _) in DO_NOT_ENABLE {
            let d = decide_in(PolicyMode::Strict, step);
            assert!(!d.is_allowed(), "{step} must be refused");
        }
        for step in [
            "empty",
            "structure_starts",
            "structure_references",
            "biomes",
            "noise",
            "surface",
            "carvers",
            "features",
            "initialize_light",
            "light",
            "spawn",
            "heightmaps",
            "full",
        ] {
            assert_eq!(
                decide_in(PolicyMode::Strict, step),
                Decision::KeepJava {
                    reason: "not proven (zero-diff gate not passed)"
                },
                "{step} is unproven and must stay Java"
            );
        }
    }

    #[test]
    fn do_not_enable_refusals_carry_their_reason() {
        for (step, reason) in DO_NOT_ENABLE {
            assert_eq!(
                decide_in(PolicyMode::Strict, step),
                Decision::KeepJava { reason },
                "{step} must be refused with its registry reason"
            );
            assert!(!decide_in(PolicyMode::Strict, step).is_allowed());
        }
    }

    // --- coverage helper -------------------------------------------------------

    #[test]
    fn coverage_ratio_sanity() {
        assert_eq!(coverage_ratio(0, 0), 0.0); // empty batch: no claim
        assert_eq!(coverage_ratio(100, 0), 0.0);
        assert_eq!(coverage_ratio(0, 100), 0.0);
        assert_eq!(coverage_ratio(25, 100), 0.25);
        assert_eq!(coverage_ratio(100, 100), 1.0);
        assert_eq!(coverage_ratio(1, 3), 1.0 / 3.0);
        assert!(coverage_ratio(1, 10_000) > 0.0);
    }
}
