#!/usr/bin/env python3
"""P500 bench generator — revives the P500 benchmark methodology as a
standalone JNI bench-driver for the Crussty CE native surface.

Reads native/JNI_EXPORTS.manifest (single source of truth) and emits into
bench/p500/java/:

  p500/groups.tsv        group table: fqcn, sig, methods (tab-separated)
  p500/Group.java        interface: setup(int strategy), methods(), call(int idx)
  p500/G<gid>.java       one class per bench group: typed arg fields, four
                         argument strategies, DIRECT static calls into the
                         native kernels (no reflection in the hot loop)
  <fqcn>.java stubs      `public static native` declarations for ALL exports,
                         so cross-kernel JNI callbacks resolve in the bench JVM
  p500/Bench.java        driver: one group per JVM, probe strategies, warmup,
                         time-bounded batches, median of 5, DCE-proof sink

P500 methodology notes:
  * A "group" = (fqcn, sig) whose method set contains >= 1 `old*` kernel.
    Every method of the group is measured with IDENTICAL arguments, so the
    old-vs-optimized comparison is apples-to-apples.
  * One JVM fork per group: a misbehaving closed-source kernel (SIGSEGV on
    unexpected input) cannot poison the rest of the run.
  * The last `[J` of a descriptor is treated as the summary/dst array.
"""
import os, collections

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MANIFEST = os.path.join(ROOT, "native", "JNI_EXPORTS.manifest")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "java")

PRIM = {"I": "int", "J": "long", "D": "double", "F": "float",
        "Z": "boolean", "B": "byte", "S": "short", "C": "char"}

def load_rows():
    rows = []
    with open(MANIFEST) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "|" not in line:
                continue
            cls, m, sig, sym = line.split("|")
            body = sym[len("Java_"):]
            fqcn = body[: body.rfind("_")].replace("_", ".")
            rows.append({"cls": cls, "fqcn": fqcn, "method": m, "sig": sig})
    return rows

def parse_params(sig):
    """'(ILjava/lang/String;[J)I' -> [('I','int'), ('L','java.lang.String'), ('[J','long[]')]"""
    params, i = [], 1
    while i < len(sig):
        if sig[i] == ")":
            break
        dims = 0
        while sig[i] == "[":
            dims += 1
            i += 1
        c = sig[i]
        i += 1
        if c == "L":
            j = sig.index(";", i)
            comp = sig[i:j].replace("/", ".")
            i = j + 1
        else:
            comp = PRIM[c]
        params.append(("[" * dims, comp))
    return params

def jtype(dims, comp):
    n = len(dims)
    return comp + "[]" * n

def groups_of(rows):
    by = collections.defaultdict(dict)
    for r in rows:
        by[(r["fqcn"], r["sig"])][r["method"]] = r
    out = []
    for (fqcn, sig), ms in sorted(by.items()):
        if any(m.startswith("old") for m in ms):
            out.append((fqcn, sig, sorted(ms)))
    return out

# ---------------------------------------------------------------- stubs ----

def stub_source(fqcn, methods):
    pkg, short = fqcn.rsplit(".", 1) if "." in fqcn else ("", fqcn)
    lines = []
    if pkg:
        lines.append(f"package {pkg};")
    lines.append("")
    lines.append("/** P500 bench stub — generated by bench/p500/gen_p500_bench.py. DO NOT EDIT.")
    lines.append(" *  Declares Crussty CE exports as static natives so the JVM binds them")
    lines.append(" *  to libpaper_native_jni.so by exact JNI symbol name. */")
    lines.append("public final class %s {" % short)
    for m, sig in sorted(methods):
        ps = parse_params(sig)
        args = ", ".join(f"{jtype(d, c)} a{k}" for k, (d, c) in enumerate(ps))
        ret = sig[sig.rindex(")") + 1:]
        ret_t = {"V": "void"}.get(ret, PRIM.get(ret, ret.replace("/", ".")))
        lines.append(f"    public static native {ret_t} {m}({args});")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)

# -------------------------------------------------------- group classes ----

CONSTS = {
    "long":   ["0x5DEECE66DL + 12345L", "0x5DEECE66DL + 67890L", "0x5DEECE66DL + 13579L"],
    "double": ["0.5", "-12.25", "3.75"],
    "float":  ["1.5f", "-7.25f", "2.125f"],
}

def group_class(gid, fqcn, sig, methods):
    ps = parse_params(sig)
    ret = sig[sig.rindex(")") + 1:]
    lines = []
    A = lines.append
    # NOTE: group classes live in the DEFAULT package on purpose — several
    # PaperNative* stubs have no package, and named packages cannot reference
    # default-package classes in Java. Default-package classes CAN import
    # p500.Group, so the driver talks to them through the interface + forName.
    if "." in fqcn:
        A(f"import {fqcn};")
    A("")
    A("/** P500 bench group %d — generated. DO NOT EDIT." % gid)
    A(" *  %s%s -> [%s]" % (fqcn, sig, ", ".join(methods)))
    A(" *  Typed argument fields + direct static calls into the kernels:")
    A(" *  zero reflection in the hot loop, zero boxing of kernel results. */")
    A("public final class G%d implements p500.Group {" % gid)
    A("    private static final int[] SMALL = {7, 31, 3, 15, 63, 1, 9, 21};")
    # typed fields
    for k, (d, c) in enumerate(ps):
        A("    static %s p%d;" % (jtype(d, c), k))
    A("")
    A("    @Override public String fqcn() { return \"%s\"; }" % fqcn)
    A("    @Override public String sig() { return \"%s\"; }" % sig)
    names = ", ".join('"%s"' % m for m in methods)
    A("    @Override public String[] methods() { return new String[]{%s}; }" % names)
    A("")

    # setup: four strategies
    A("    @Override public void setup(int s) {")
    A("        switch (s) {")
    for strat, n, strings in [(0, "p500.Bench.N", True), (1, "16", True), (2, "1", True), (3, "16", False)]:
        A("        case %d -> setup(%s, %s);" % (strat, n, "true" if strings else "false"))
    A("        }")
    A("    }")
    A("    private static void setup(int n, boolean strings) {")
    ip = 0
    small = 0
    jn = 0
    dn = 0
    dst_seen = False
    # find index of last [J param (dst) — comps are JAVA type names here
    dst_idx = max((k for k, (d, c) in enumerate(ps) if d and c == "long"), default=-1)
    for k, (d, c) in enumerate(ps):
        if d:
            if k == dst_idx:
                A("            p%d = new long[64];" % k)
            elif c == "long":
                A("            p%d = new long[Math.max(8, n)]; for (int i = 0; i < p%d.length; i++) p%d[i] = (0x9E3779B97F4A7C15L * i) ^ (i * 0xC2B2AE3D27D4EB4FL);" % (k, k, k))
            elif c == "int":
                A("            p%d = new int[Math.max(8, n)]; for (int i = 0; i < p%d.length; i++) p%d[i] = (int) ((i * 0x9E3779B1L) & 0x3FF);" % (k, k, k))
            elif c == "double":
                A("            p%d = new double[Math.max(8, n)]; for (int i = 0; i < p%d.length; i++) p%d[i] = (i %% 97) * 0.5 - 24.0;" % (k, k, k))
            elif c == "float":
                A("            p%d = new float[Math.max(8, n)]; for (int i = 0; i < p%d.length; i++) p%d[i] = (i %% 61) * 0.25f - 7.5f;" % (k, k, k))
            elif c == "boolean":
                A("            p%d = new boolean[Math.max(8, n)]; for (int i = 0; i < p%d.length; i++) p%d[i] = (i %% 3) != 0;" % (k, k, k))
            elif c == "byte":
                A("            p%d = new byte[256]; for (int i = 0; i < 256; i++) p%d[i] = (byte) ((i * 7919) & 0xFF);" % (k, k))
            elif c in ("java.lang.String", "java.lang.Object"):
                A("            p%d = new Object[Math.max(8, n)];" % k)
                if strings:
                    A("            for (int i = 0; i < p%d.length; i++) p%d[i] = \"plugin-\" + i;" % (k, k))
            else:
                A("            p%d = new %s[Math.max(8, n)];" % (k, c))
        else:
            if c == "int":
                v = "n" if ip == 0 else "SMALL[%d]" % (small % 8)
                ip += 1
                small += 1
                A("            p%d = %s;" % (k, v))
            elif c == "long":
                A("            p%d = %s;" % (k, CONSTS["long"][jn % 3]))
                jn += 1
            elif c == "double":
                A("            p%d = %s;" % (k, CONSTS["double"][dn % 3]))
                dn += 1
            elif c == "float":
                A("            p%d = %s;" % (k, CONSTS["float"][small % 3]))
            elif c == "boolean":
                A("            p%d = %s;" % (k, "true" if (small % 2 == 0) else "false"))
                small += 1
            elif c == "byte":
                A("            p%d = (byte) 65;" % k)
            elif c == "short":
                A("            p%d = (short) 512;" % k)
            elif c == "char":
                A("            p%d = 'x';" % k)
            elif c == "java.lang.String":
                A("            p%d = p500.Bench.tmpDir();" % k)
            else:
                A("            p%d = null;" % k)
    A("    }")
    A("")

    # call(idx): direct static invocation, result folded into a long accumulator
    A("    @Override public long call(int idx) {")
    A("        long acc;")
    A("        switch (idx) {")
    args_of = ", ".join("p%d" % k for k in range(len(ps)))
    for mi, m in enumerate(methods):
        if ret == "I":
            expr = f"{fqcn}.{m}({args_of})"
            body = f"acc = {expr};"
        elif ret == "J":
            body = f"acc = {fqcn}.{m}({args_of});"
        elif ret == "D":
            body = f"acc = Double.doubleToRawLongBits({fqcn}.{m}({args_of}));"
        elif ret == "F":
            body = f"acc = Float.floatToIntBits({fqcn}.{m}({args_of}));"
        elif ret == "Z":
            body = f"acc = {fqcn}.{m}({args_of}) ? 1L : 0L;"
        else:
            body = f"acc = 0L; {fqcn}.{m}({args_of});"
        A(f"        case {mi} -> {{ {body} }}")
    A("        default -> acc = 0L;")
    A("        }")
    A("        acc = acc * 31 + (dst0() ^ dst1());")
    A("        return acc;")
    A("    }")
    A("    static long dst0() {")
    if dst_idx >= 0:
        A("        return p%d.length > 0 ? p%d[0] : 0L;" % (dst_idx, dst_idx))
    else:
        A("        return 0L;")
    A("    }")
    A("    static long dst1() {")
    if dst_idx >= 0:
        A("        return p%d.length > 1 ? p%d[1] : 0L;" % (dst_idx, dst_idx))
    else:
        A("        return 0L;")
    A("    }")
    A("}")
    A("")
    return "\n".join(lines)

# -------------------------------------------------------------- Bench ------

BENCH = r'''package p500;

import java.io.*;
import java.nio.file.*;
import java.util.*;

/**
 * P500 bench driver — one group per JVM: args <gid>. TSV on stdout.
 *
 * Fairness protocol (learned the hard way, see results/):
 *  - args are REBUILT (fresh arrays) before every method measurement: some
 *    kernels mutate their inputs (e.g. *RemoveIfSummary), so sharing arrays
 *    across methods would hand the first-measured kernel more work;
 *  - every method is measured twice — a forward pass and a reverse pass —
 *    and the LOWER of the two medians is reported (min-of-two kills the
 *    residual order bias: forward favours early methods, reverse favours
 *    late ones);
 *  - per-method strategy ladder: if a kernel rejects the default shape
 *    (n = N), it is retried with n = 16 / 1 / null-objects before ERR;
 *  - time-bounded batches (~120ms), median of 5, DCE-proof sink.
 */
public final class Bench {
    public static volatile long SINK;
    public static int N = Integer.getInteger("p500.n", 256);

    static String TMP;
    /** Shared temp dir with a few files — used for kernels taking a path argument. */
    public static synchronized String tmpDir() {
        if (TMP == null) {
            try {
                Path d = Files.createTempDirectory("p500-scan");
                for (int k = 0; k < 3; k++) Files.writeString(d.resolve("file" + k + ".jar"), "x");
                Files.createDirectories(d.resolve("sub"));
                Files.writeString(d.resolve("sub").resolve("inner.jar"), "y");
                TMP = d.toString();
            } catch (IOException e) { TMP = "."; }
        }
        return TMP;
    }

    public static void main(String[] argv) throws Exception {
        for (String p : System.getProperty("p500.libs", "").split(File.pathSeparator))
            if (!p.isBlank()) System.load(p);
        int gid = Integer.parseInt(argv[0]);
        Group g;
        try {
            g = (Group) Class.forName("G" + gid).getDeclaredConstructor().newInstance();
        } catch (ClassNotFoundException e) {
            System.out.println("SKIP\t" + gid + "\t?\t?\tno group class");
            return;
        }
        System.err.println("group " + gid + ": " + g.fqcn() + g.sig() + " -> " + Arrays.toString(g.methods()));
        benchGroup(gid, g);
        System.out.println("SINK\t" + SINK);
        System.out.flush();
    }

    // ---------- measurement ----------

    static final int ROUNDS = 5;   // measured batches per pass
    static final int WARM = 2;     // discarded batches per pass
    static final long BATCH_NS = 120_000;

    static void benchGroup(int gid, Group g) {
        String[] names = g.methods();
        int n = names.length;
        int[] strategy = new int[n];       // per-method surviving arg strategy
        boolean[] usable = new boolean[n]; // method survived at least one strategy
        double[] single = new double[n];   // one timed call, for the SLOW lane

        for (int i = 0; i < n; i++) {
            for (int s = 0; s < 4 && !usable[i]; s++) {
                try {
                    g.setup(s);
                    long t0 = System.nanoTime();
                    SINK += g.call(i);
                    single[i] = System.nanoTime() - t0;
                    strategy[i] = s;
                    usable[i] = true;
                } catch (UnsatisfiedLinkError e) {
                    System.err.println("FATAL unbound: " + names[i] + ": " + e);
                    System.exit(3);
                } catch (Throwable t) {
                    System.err.println("  probe " + names[i] + " strategy " + s + ": "
                            + t.getClass().getSimpleName());
                }
            }
            if (!usable[i]) report(gid, g, names[i], Double.NaN, Double.NaN, Double.NaN, "ERR all-strategies");
        }

        double[] medF = onePass(g, names, usable, strategy, single, false);
        double[] medR = onePass(g, names, usable, strategy, single, true);

        for (int i = 0; i < n; i++) {
            if (!usable[i]) continue;
            if (single[i] > 250_000_000L) {
                // SLOW lane: 3 calls, mean (fresh args each call)
                g.setup(strategy[i]);
                long acc = 0;
                for (int k = 0; k < 3; k++) {
                    long a = System.nanoTime(); SINK += g.call(i); acc += System.nanoTime() - a;
                    g.setup(strategy[i]);
                }
                report(gid, g, names[i], acc / 3.0, acc / 3.0, acc / 3.0, "SLOW s" + strategy[i]);
            } else {
                double med = Math.min(medF[i], medR[i]);
                report(gid, g, names[i], med, med, med, "OK s" + strategy[i]);
            }
        }
    }

    /** One full pass over the group. Forward = alphabetical order, reverse = the opposite. */
    static double[] onePass(Group g, String[] names, boolean[] usable, int[] strategy,
                            double[] single, boolean reverse) {
        double[] med = new double[names.length];
        for (int x = 0; x < names.length; x++) {
            int i = reverse ? names.length - 1 - x : x;
            if (!usable[i]) continue;
            g.setup(strategy[i]);               // fresh args for EVERY method
            if (single[i] > 250_000_000L) { med[i] = single[i]; continue; }
            try {
                double[] s = new double[ROUNDS];
                for (int w = 0; w < WARM; w++) runBatch(g, i, 40_000);
                for (int r = 0; r < ROUNDS; r++) s[r] = runBatch(g, i, BATCH_NS);
                Arrays.sort(s);
                med[i] = s[s.length / 2];
            } catch (Throwable t) {
                System.err.println("  batch " + names[i] + " (" + (reverse ? "rev" : "fwd")
                        + "): " + t.getClass().getSimpleName());
                med[i] = Double.NaN;
            }
        }
        return med;
    }

    static double runBatch(Group g, int idx, long budgetNs) {
        long calls = 0, t0 = System.nanoTime(), el;
        do {
            for (int k = 0; k < 8; k++) SINK += g.call(idx);
            calls += 8;
            el = System.nanoTime() - t0;
        } while (el < budgetNs);
        return (double) el / calls;
    }

    static void report(int gid, Group g, String method, double med, double min, double max, String status) {
        String kind = method.startsWith("old") ? "old" : "alt";
        System.out.printf(Locale.ROOT, "RESULT\t%d\t%s\t%s\t%s\t%s\t%.1f\t%.1f\t%.1f\t%s%n",
                gid, g.fqcn(), g.sig(), method, kind, med, min, max, status);
        System.out.flush();
        System.err.println("  " + method + " -> " + status + " "
                + (Double.isNaN(med) ? "-" : String.format(Locale.ROOT, "%.1f ns/op", med)));
    }
}
'''

GROUP_IFACE = '''package p500;

/** P500 bench group contract (generated set). */
public interface Group {
    String fqcn();
    String sig();
    String[] methods();
    void setup(int strategy);
    long call(int idx);
}
'''

def main():
    rows = load_rows()
    groups = groups_of(rows)
    os.makedirs(os.path.join(OUT, "p500"), exist_ok=True)

    with open(os.path.join(OUT, "p500", "groups.tsv"), "w") as f:
        for fqcn, sig, methods in groups:
            f.write(f"{fqcn}\t{sig}\t{','.join(methods)}\n")

    with open(os.path.join(OUT, "p500", "Group.java"), "w") as f:
        f.write(GROUP_IFACE)
    with open(os.path.join(OUT, "p500", "Bench.java"), "w") as f:
        f.write(BENCH)

    for gid, (fqcn, sig, methods) in enumerate(groups):
        with open(os.path.join(OUT, "p500", f"G{gid}.java"), "w") as f:
            f.write(group_class(gid, fqcn, sig, methods))

    by_class = collections.defaultdict(set)
    for r in rows:
        by_class[r["fqcn"]].add((r["method"], r["sig"]))
    for fqcn, ms in sorted(by_class.items()):
        path = os.path.join(OUT, *fqcn.split(".")) + ".java"
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(stub_source(fqcn, ms))

    print(f"groups: {len(groups)}, stub classes: {len(by_class)}, stub methods: {len(rows)}")
    for gid, (fqcn, sig, methods) in enumerate(groups):
        print(f"{gid}\t{fqcn}\t{sig}\t{','.join(methods)}")

if __name__ == "__main__":
    main()
