import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * FloorBench — JNI-floor micro-benchmark (task B11).
 *
 * WHY: results/P500_REPORT.md showed ~40 plugin/loading kernels pinned at
 * ~115 ns/call — suspected to be the pure JNI transition floor of this JVM
 * (call args nearly irrelevant at that level). This bench measures that
 * floor directly, standalone, with three lanes:
 *
 *   LANE-A  pure-Java baselines (no natives needed):
 *           empty static method (~1 ns), same-shape 4-arg static,
 *           volatile SINK fold (harness overhead), System.nanoTime().
 *
 *   LANE-B  five Crussty CE kernels that P500_REPORT.md measured at
 *           median < 150 ns — i.e. pure-floor candidates. Each is called
 *           with the IDENTICAL argument shapes the P500 harness used
 *           (strategy 0, N=256, generated by gen_p500_bench.py), so the
 *           numbers are directly comparable with P500_REPORT.md:
 *             g32 PaperNativePluginNameLog.newArrayListSortSummary      112.7 ns
 *             g35 PaperNativeRangeChoice.oldFillArraySummary            111.9 ns
 *             g39 PaperNativeSpigotLoadOrderDependency.newLoadAfterBuildSummary 114.5 ns
 *             g42 PaperNativeStaticCacheGet.oldBatchSummary             138.2 ns
 *             g33 PaperNativePluginStartupRollup.newSummary             143.1 ns
 *
 *   LANE-C  JNI transition tax, indirect A/B:
 *             native  PaperNativeClimateParameterDistance.subtractFirstDistanceSum
 *                     ([J[J[J[J)I   — P500 median 651.8 ns
 *             java-approx lanes implementing a PLAUSIBLE reconstruction of
 *             "distance sum over packed coordinates" in pure Java at three
 *             work levels (unpacked 6x10-bit field distance / raw abs-diff /
 *             array-touch). SEMANTICS NOT VERIFIED — the closed kernel's real
 *             body is unknown; these lanes only bound what the pure-Java part
 *             of comparable work costs, they do NOT claim parity.
 *
 * Protocol (mirrors p500.Bench): prebuilt args (fresh arrays per lane,
 * kernels may mutate), warmup, COUNT calls split into 5 timed segments,
 * median/min/max ns-per-op, every result folded into a volatile SINK
 * against DCE. One JVM for all lanes — every kernel here survived the P500
 * retry ladder, so fork-per-group isolation is not needed.
 *
 * Output: RESULT/SUMMARY TSV lines on stdout (-> floor_report.tsv),
 * human progress on stderr (-> floor_run.log).
 *
 * Drop-in: FloorGroup (same dir) exposes the same lanes through the
 * p500.Group contract used by the P500 harness, so the floor lanes can be
 * driven from the injected server JVM (bootstrap-loader classes) with the
 * p500 group machinery. p500.Bench itself hardcodes Class.forName("G"+gid),
 * so driving FloorGroup needs a tiny driver loop or a future Bench patch.
 *
 * Run: bench/p500/jni_floor/FloorRun.sh   (JDK resolution + compile + flags + run)
 */
public final class FloorBench {

    // ---------------- harness state (mirrors p500.Bench conventions) ---------

    /** DCE-proof accumulator; folded into every lane call. */
    public static volatile long SINK;

    /** total measured calls per lane (task spec: 10M). */
    static long COUNT = Long.getLong("floor.count", 10_000_000L);
    /** calls between timer reads. */
    static int BATCH = Integer.getInteger("floor.batch", 16);
    /** timed segments per lane (median of these). */
    static int SEGMENTS = Integer.getInteger("floor.segments", 5);
    /** warmup calls per lane. */
    static long WARM = Long.getLong("floor.warm", 200_000L);
    /** array length "n" used by the P500 strategy-0 shapes. */
    static int N = Integer.getInteger("floor.n", 256);

    static final int[] SMALL = {7, 31, 3, 15, 63, 1, 9, 21};

    private interface Lane { long call(); }

    private record LaneDef(String name, String kind, String fqcn, String sig,
                           boolean nativeLane, Lane lane) {}

    // ---------------- prebuilt argument state (P500 strategy-0 shapes) -------

    // PluginNameLog / SpigotLoadOrderDependency / PluginStartupRollup shapes
    static int aInt;
    static Object[] aObj1, aObj2, aObj3;
    static long[] aDst;                      // shared 64-slot dst (last [J)
    // RangeChoice shape
    static double[] aD0; static int[] aI1, aI2, aI3;
    // StaticCacheGet shape
    static int[] aI5;
    // ClimateParameterDistance shape
    static long[] aC0, aC1, aC2;
    static String aTmpDir;

    static synchronized String tmpDir() {
        try {
            Path d = Files.createTempDirectory("floor-scan");
            for (int k = 0; k < 3; k++) Files.writeString(d.resolve("file" + k + ".jar"), "x");
            Files.createDirectories(d.resolve("sub"));
            Files.writeString(d.resolve("sub").resolve("inner.jar"), "y");
            return d.toString();
        } catch (IOException e) { return "."; }
    }

    /** Fresh args per lane — some kernels mutate their inputs (see P500 notes). */
    static void buildArgs() {
        int n = N;
        aInt = n;
        aObj1 = new Object[Math.max(8, n)];
        aObj2 = new Object[Math.max(8, n)];
        aObj3 = new Object[Math.max(8, n)];
        aDst  = new long[64];
        aD0 = new double[Math.max(8, n)];
        aI1 = new int[Math.max(8, n)];
        aI2 = new int[Math.max(8, n)];
        aI3 = new int[Math.max(8, n)];
        for (int i = 0; i < Math.max(8, n); i++) {
            aD0[i] = (i % 97) * 0.5 - 24.0;
            int v = (int) ((i * 0x9E3779B1L) & 0x3FF);
            aI1[i] = v; aI2[i] = v; aI3[i] = v;
        }
        aI5 = new int[Math.max(8, n)];
        for (int i = 0; i < aI5.length; i++) aI5[i] = (int) ((i * 0x9E3779B1L) & 0x3FF);
        aC0 = new long[Math.max(8, n)];
        aC1 = new long[Math.max(8, n)];
        aC2 = new long[Math.max(8, n)];
        for (int i = 0; i < Math.max(8, n); i++) {
            long v = (0x9E3779B97F4A7C15L * i) ^ (i * 0xC2B2AE3D27D4EB4FL);
            aC0[i] = v; aC1[i] = v; aC2[i] = v;
        }
        aTmpDir = tmpDir();
    }

    // dst fold identical to the generated P500 groups (acc*31 + dst0^dst1)
    static long fold(long acc) {
        long d0 = aDst.length > 0 ? aDst[0] : 0L;
        long d1 = aDst.length > 1 ? aDst[1] : 0L;
        return acc * 31 + (d0 ^ d1);
    }

    // ---------------- LANE-A: pure Java baselines ----------------------------

    static long emptyStatic() { return 0L; }

    /** 16 empty calls inside the lane: the volatile SINK fold is paid once
     *  per 16 calls, so median/16 approximates the naked Java call cost. */
    static long emptyStaticBatched16() {
        long s = 0;
        for (int k = 0; k < 16; k++) s += emptyStatic();
        return s;
    }

    static long emptyStatic4args(int n, Object[] o1, Object[] o2, long[] dst) {
        // signature-identical to PaperNativePluginNameLog kernels: isolates the
        // transition cost for the exact same argument shape.
        return n ^ o1.length ^ o2.length ^ dst.length;
    }

    // ---------------- LANE-C: java-approx climate distance -------------------
    // PLAUSIBLE reconstruction only (see class javadoc). Packed point = 6
    // signed 10-bit fields, vanilla Climate.RTree style; "subtractFirst" read
    // as: distance of b[i] and c[i] against the FIRST packed point a[0].

    static long signed10(long v, int f) {
        long x = (v >>> (f * 10)) & 0x3FFL;
        return (x & 0x200L) != 0 ? x - 0x400L : x;
    }

    static long packedDistance(long p, long q) {
        long d = 0;
        for (int f = 0; f < 6; f++) d += Math.abs(signed10(p, f) - signed10(q, f));
        return d;
    }

    static int javaApproxClimateDistanceSum(long[] a, long[] b, long[] c, long[] dst) {
        long ref = a.length > 0 ? a[0] : 0L;
        long sum = 0L;
        for (int i = 0; i < b.length && i < c.length; i++)
            sum += packedDistance(b[i], ref) + packedDistance(c[i], ref);
        if (dst.length > 0) dst[0] = sum;
        return (int) Math.min(Integer.MAX_VALUE, sum);
    }

    static int javaApproxSubtractFirstRaw(long[] a, long[] b, long[] c, long[] dst) {
        long ref = a.length > 0 ? a[0] : 0L;
        long sum = 0L;
        for (int i = 0; i < b.length && i < c.length; i++)
            sum += Math.abs(b[i] - ref) + Math.abs(c[i] - ref);
        if (dst.length > 0) dst[0] = sum;
        return (int) Math.min(Integer.MAX_VALUE, sum);
    }

    static int javaApproxTouch(long[] a, long[] b, long[] c, long[] dst) {
        long s = 0L;
        for (int i = 0; i < a.length; i++) s ^= a[i] ^ b[i] ^ c[i];
        if (dst.length > 0) dst[0] = s;
        return (int) s;
    }

    // ---------------- lane table ---------------------------------------------

    static List<LaneDef> lanes() {
        List<LaneDef> L = new ArrayList<>();
        boolean nat = NATIVES_OK;
        // LANE-A — pure Java, always available
        L.add(new LaneDef("java_emptyStatic", "java-baseline", "FloorBench", "()J", false,
                () -> emptyStatic()));
        L.add(new LaneDef("java_emptyStaticBatched16", "java-baseline", "FloorBench", "()J", false,
                () -> emptyStaticBatched16()));
        L.add(new LaneDef("java_emptyStatic4args", "java-baseline", "FloorBench",
                "(I[Ljava/lang/Object;[Ljava/lang/Object;[J)I", false,
                () -> emptyStatic4args(aInt, aObj1, aObj2, aDst)));
        L.add(new LaneDef("java_sinkVolatileFold", "java-baseline", "FloorBench", "(J)V", false,
                () -> { long v = SINK; SINK = v + 1L; return v; }));
        L.add(new LaneDef("java_nanoTimeCall", "java-baseline", "FloorBench", "()J", false,
                () -> { long t = System.nanoTime(); return t ^ (t >>> 32); }));
        // LANE-B — P500 sub-150ns kernels = JNI floor candidates
        if (nat) {
            L.add(new LaneDef("jni_g32_PluginNameLog_newArrayListSortSummary", "jni-floor",
                    "PaperNativePluginNameLog", "(I[Ljava/lang/Object;[Ljava/lang/Object;[J)I", true,
                    () -> fold(PaperNativePluginNameLog.newArrayListSortSummary(aInt, aObj1, aObj2, aDst))));
            L.add(new LaneDef("jni_g35_RangeChoice_oldFillArraySummary", "jni-floor",
                    "PaperNativeRangeChoice", "([D[I[I[II[J)I", true,
                    () -> fold(PaperNativeRangeChoice.oldFillArraySummary(aD0, aI1, aI2, aI3, aInt, aDst))));
            L.add(new LaneDef("jni_g39_SpigotLoadOrderDependency_newLoadAfterBuildSummary", "jni-floor",
                    "PaperNativeSpigotLoadOrderDependency", "(I[Ljava/lang/Object;[J)I", true,
                    () -> fold(PaperNativeSpigotLoadOrderDependency.newLoadAfterBuildSummary(aInt, aObj1, aDst))));
            L.add(new LaneDef("jni_g42_StaticCacheGet_oldBatchSummary", "jni-floor",
                    "PaperNativeStaticCacheGet", "(IIIII[I[J)I", true,
                    () -> fold(PaperNativeStaticCacheGet.oldBatchSummary(
                            aInt, SMALL[1], SMALL[2], SMALL[3], SMALL[4], aI5, aDst))));
            L.add(new LaneDef("jni_g33_PluginStartupRollup_newSummary", "jni-floor",
                    "PaperNativePluginStartupRollup",
                    "(I[Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Object;[J)I", true,
                    () -> fold(PaperNativePluginStartupRollup.newSummary(aInt, aObj1, aTmpDir, aObj2, aObj3, aDst))));
            // LANE-C — native climate kernel vs java-approx
            L.add(new LaneDef("jni_g06_ClimateParameterDistance_subtractFirstDistanceSum", "jni-tax-native",
                    "PaperNativeClimateParameterDistance", "([J[J[J[J)I", true,
                    () -> fold(PaperNativeClimateParameterDistance.subtractFirstDistanceSum(aC0, aC1, aC2, aDst))));
        }
        L.add(new LaneDef("javaApproxClimateDistanceSum_unpacked6x10", "java-approx", "FloorBench",
                "([J[J[J[J)I", false,
                () -> fold(javaApproxClimateDistanceSum(aC0, aC1, aC2, aDst))));
        L.add(new LaneDef("javaApproxSubtractFirst_raw", "java-approx", "FloorBench",
                "([J[J[J[J)I", false,
                () -> fold(javaApproxSubtractFirstRaw(aC0, aC1, aC2, aDst))));
        L.add(new LaneDef("javaApproxTouch3Arrays", "java-approx", "FloorBench",
                "([J[J[J[J)I", false,
                () -> fold(javaApproxTouch(aC0, aC1, aC2, aDst))));
        return L;
    }

    // ---------------- natives loading (same convention as p500.Bench) --------

    static boolean NATIVES_OK;
    static String NATIVES_NOTE = "";

    static void loadNatives() {
        String libs = System.getProperty("floor.libs", "");
        if (libs.isBlank()) {
            NATIVES_OK = false;
            NATIVES_NOTE = "no -Dfloor.libs given";
            return;
        }
        try {
            for (String p : libs.split(File.pathSeparator))
                if (!p.isBlank()) System.load(p);
            NATIVES_OK = true;
        } catch (Throwable t) {
            NATIVES_OK = false;
            NATIVES_NOTE = t.getClass().getSimpleName() + ": " + t.getMessage();
        }
    }

    // ---------------- measurement (P500-style: warmup, segments, median) -----

    static double[] measure(Lane lane) {
        for (long k = 0; k < WARM; k++) SINK += lane.call();
        long per = Math.max(BATCH * 2L, COUNT / SEGMENTS);
        double[] rates = new double[SEGMENTS];
        for (int s = 0; s < SEGMENTS; s++) {
            long calls = 0, t0 = System.nanoTime(), el;
            do {
                for (int k = 0; k < BATCH; k++) SINK += lane.call();
                calls += BATCH;
                el = System.nanoTime() - t0;
            } while (calls < per);
            rates[s] = (double) el / calls;
        }
        Arrays.sort(rates);
        return rates;
    }

    static String fmt(double v) {
        return String.format(Locale.ROOT, "%.1f", v);
    }

    static final Map<String, double[]> BY_NAME = new HashMap<>();

    static void report(LaneDef d) {
        double[] s;
        try {
            buildArgs();
            s = measure(d.lane());
        } catch (UnsatisfiedLinkError e) {
            System.out.printf(Locale.ROOT,
                    "RESULT\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\tNO-NATIVE %s%n",
                    d.name(), d.kind(), d.fqcn(), d.sig(), "-", "-", "-", "-", e.getMessage());
            System.out.flush();
            System.err.println("  " + d.name() + " -> NO-NATIVE: " + e.getMessage());
            return;
        } catch (Throwable t) {
            System.out.printf(Locale.ROOT,
                    "RESULT\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\tERR %s%n",
                    d.name(), d.kind(), d.fqcn(), d.sig(), "-", "-", "-", "-",
                    t.getClass().getSimpleName());
            System.out.flush();
            System.err.println("  " + d.name() + " -> ERR " + t);
            return;
        }
        BY_NAME.put(d.name(), s);
        System.out.printf(Locale.ROOT, "RESULT\t%s\t%s\t%s\t%s\t%s\t%s\t%s\tOK%n",
                d.name(), d.kind(), d.fqcn(), d.sig(),
                fmt(s[s.length / 2]), fmt(s[0]), fmt(s[s.length - 1]));
        System.out.flush();
        System.err.println("  " + d.name() + " -> " + fmt(s[s.length / 2]) + " ns/op"
                + " (min " + fmt(s[0]) + ", max " + fmt(s[s.length - 1]) + ")");
    }

    static double laneMedian(String name) {
        double[] s = BY_NAME.get(name);
        return s == null ? Double.NaN : s[s.length / 2];
    }

    // ---------------- main ----------------------------------------------------

    public static void main(String[] argv) {
        long t0 = System.nanoTime();
        loadNatives();
        System.err.println("FloorBench: floor.count=" + COUNT + " floor.n=" + N
                + " segments=" + SEGMENTS + " batch=" + BATCH
                + " natives=" + (NATIVES_OK ? "LOADED" : "UNAVAILABLE (" + NATIVES_NOTE + ")"));
        if (!NATIVES_OK) {
            System.out.println("NOTE\tnatives-unavailable\t" + NATIVES_NOTE
                    + "\trun inside the live server JVM (see FloorRun.sh / reports/B11) or check -Dfloor.libs");
        }

        List<LaneDef> lanes = lanes();
        // probe every native lane once before measuring (bind check, p500-style)
        buildArgs();
        List<LaneDef> usable = new ArrayList<>();
        for (LaneDef d : lanes) {
            if (d.nativeLane()) {
                try {
                    SINK += d.lane().call();
                } catch (UnsatisfiedLinkError e) {
                    System.out.printf(Locale.ROOT,
                            "RESULT\t%s\t%s\t%s\t%s\t%s\t%s\t%s\tNO-NATIVE %s%n",
                            d.name(), d.kind(), d.fqcn(), d.sig(), "-", "-", "-", e.getMessage());
                    System.err.println("  probe " + d.name() + " -> NO-NATIVE: " + e.getMessage());
                    continue;
                } catch (Throwable t) {
                    System.out.printf(Locale.ROOT,
                            "RESULT\t%s\t%s\t%s\t%s\t%s\t%s\t%s\tERR %s%n",
                            d.name(), d.kind(), d.fqcn(), d.sig(), "-", "-", "-",
                            t.getClass().getSimpleName());
                    System.err.println("  probe " + d.name() + " -> ERR " + t);
                    continue;
                }
            }
            usable.add(d);
        }

        for (LaneDef d : usable) report(d);

        summary(usable);
        System.out.println("SINK\t" + SINK);
        System.err.printf(Locale.ROOT, "FloorBench done in %.1fs%n",
                (System.nanoTime() - t0) / 1e9);
        System.out.flush();
    }

    static void summary(List<LaneDef> usable) {
        double jniFloor = Double.NaN;
        for (String k : new String[]{
                "jni_g32_PluginNameLog_newArrayListSortSummary",
                "jni_g35_RangeChoice_oldFillArraySummary",
                "jni_g39_SpigotLoadOrderDependency_newLoadAfterBuildSummary",
                "jni_g42_StaticCacheGet_oldBatchSummary",
                "jni_g33_PluginStartupRollup_newSummary"}) {
            double m = laneMedian(k);
            if (!Double.isNaN(m)) jniFloor = Double.isNaN(jniFloor) ? m : Math.min(jniFloor, m);
        }
        double nativeClimate = laneMedian("jni_g06_ClimateParameterDistance_subtractFirstDistanceSum");
        double approxUnpacked = laneMedian("javaApproxClimateDistanceSum_unpacked6x10");
        double approxRaw = laneMedian("javaApproxSubtractFirst_raw");
        double approxTouch = laneMedian("javaApproxTouch3Arrays");

        System.out.println("# ---- SUMMARY (median ns/op; java-approx lanes are PLAUSIBLE reconstructions, NOT verified parity) ----");
        System.out.printf(Locale.ROOT, "SUMMARY\tjava_call_floor_emptyStatic\t%s%n", fmt(laneMedian("java_emptyStatic")));
        System.out.printf(Locale.ROOT, "SUMMARY\tjava_call_floor_emptyStatic_batched16_perCall\t%s%n",
                Double.isNaN(laneMedian("java_emptyStaticBatched16")) ? "-" : fmt(laneMedian("java_emptyStaticBatched16") / 16.0));
        System.out.printf(Locale.ROOT, "SUMMARY\tjava_call_floor_sameShape4args\t%s%n", fmt(laneMedian("java_emptyStatic4args")));
        System.out.printf(Locale.ROOT, "SUMMARY\tjava_harness_sinkVolatileFold\t%s%n", fmt(laneMedian("java_sinkVolatileFold")));
        System.out.printf(Locale.ROOT, "SUMMARY\tjava_nanoTimeCall\t%s%n", fmt(laneMedian("java_nanoTimeCall")));
        System.out.printf(Locale.ROOT, "SUMMARY\tjni_floor_estimate_min_of_5_sub150ns_kernels\t%s%n",
                Double.isNaN(jniFloor) ? "-" : fmt(jniFloor));
        System.out.printf(Locale.ROOT, "SUMMARY\tkernel_overhead_above_jni_floor_g32_PluginNameLog\t%s%n",
                Double.isNaN(jniFloor) ? "-" : fmt(laneMedian("jni_g32_PluginNameLog_newArrayListSortSummary") - jniFloor));
        System.out.printf(Locale.ROOT, "SUMMARY\tkernel_overhead_above_jni_floor_g35_RangeChoice\t%s%n",
                Double.isNaN(jniFloor) ? "-" : fmt(laneMedian("jni_g35_RangeChoice_oldFillArraySummary") - jniFloor));
        System.out.printf(Locale.ROOT, "SUMMARY\tkernel_overhead_above_jni_floor_g39_SpigotLoadOrderDependency\t%s%n",
                Double.isNaN(jniFloor) ? "-" : fmt(laneMedian("jni_g39_SpigotLoadOrderDependency_newLoadAfterBuildSummary") - jniFloor));
        System.out.printf(Locale.ROOT, "SUMMARY\tkernel_overhead_above_jni_floor_g42_StaticCacheGet\t%s%n",
                Double.isNaN(jniFloor) ? "-" : fmt(laneMedian("jni_g42_StaticCacheGet_oldBatchSummary") - jniFloor));
        System.out.printf(Locale.ROOT, "SUMMARY\tkernel_overhead_above_jni_floor_g33_PluginStartupRollup\t%s%n",
                Double.isNaN(jniFloor) ? "-" : fmt(laneMedian("jni_g33_PluginStartupRollup_newSummary") - jniFloor));
        System.out.printf(Locale.ROOT, "SUMMARY\tjni_g06_ClimateParameterDistance_subtractFirstDistanceSum\t%s%n",
                Double.isNaN(nativeClimate) ? "-" : fmt(nativeClimate));
        System.out.printf(Locale.ROOT, "SUMMARY\tjavaApprox_unpacked6x10_distance\t%s%n",
                Double.isNaN(approxUnpacked) ? "-" : fmt(approxUnpacked));
        System.out.printf(Locale.ROOT, "SUMMARY\tjavaApprox_rawAbsDiff\t%s%n",
                Double.isNaN(approxRaw) ? "-" : fmt(approxRaw));
        System.out.printf(Locale.ROOT, "SUMMARY\tjavaApprox_touch3Arrays\t%s%n",
                Double.isNaN(approxTouch) ? "-" : fmt(approxTouch));
        System.out.printf(Locale.ROOT, "SUMMARY\tjni_tax_upper_bound_nativeClimate_minus_javaApproxRaw\t%s%n",
                (Double.isNaN(nativeClimate) || Double.isNaN(approxRaw)) ? "-" : fmt(nativeClimate - approxRaw));
        System.out.printf(Locale.ROOT, "SUMMARY\tjni_tax_upper_bound_nativeClimate_minus_javaApproxUnpacked\t%s%n",
                (Double.isNaN(nativeClimate) || Double.isNaN(approxUnpacked)) ? "-" : fmt(nativeClimate - approxUnpacked));
        System.out.println("# jni_tax estimates subtract a java-approx work proxy from the native climate kernel;");
        System.out.println("# they bound (transition + unknown native kernel work), never claim exact parity.");
    }
}
